openapi: 3.0.0
info:
  title: Teste Drugovich
  contact: {}
  version: '1.0'
servers:

  - url: http://localhost:8085/api
    variables: {}

paths:
  /auth:
    post:
      tags:
        - Misc
      summary: Autenticação
      operationId: Auth
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
            example:
              email: admin@admin.com
              password: admin
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: {}
  /groups:
    get:
      tags:
        - Misc
      summary: Listagem de Grupos
      operationId: ListGroups
      parameters:
        - name: filter[name]
          in: query
          description: ''
          required: false
          style: form
          explode: true
          schema:
            type: string
            example: teste3
        - name: page
          in: query
          description: ''
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: {}
    post:
      tags:
        - Misc
      summary: Criação de Grupos
      operationId: CreateGroups
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGroupsRequest'
            example:
              name: Grupo teste
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: {}
  /groups/{groupId}:
    parameters:
      - name: groupId
        in: path
        required: true
        description: Id do grupo que será removido
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 1
    get:
      tags:
        - Misc
      summary: Busca de grupo por id
      operationId: FindGroup
      responses:
        '200':
          description: ''
          headers: { }
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: { }
    put:
      tags:
        - Misc
      summary: Atualização de grupo
      operationId: UpdateGroup
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGroupRequest'
            example:
              name: Teste 2
        required: true
      responses:
        '200':
          description: ''
          headers: { }
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: { }
    delete:
      tags:
        - Misc
      summary: Deleta grupo por id
      operationId: DeleteGroup
      responses:
        '200':
          description: 'Grupo deletado e retorna json do objeto removido'
          headers: {}
        '404':
          description: 'Grupo não encontrado'
          headers: {}
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: {}
  /customers:
    get:
      tags:
        - Misc
      summary: Listagem de Clientes
      operationId: ListCustomers
      parameters:
        - name: filter[name]
          in: query
          description: ''
          required: false
          style: form
          explode: true
          schema:
            type: string
            example: ''
        - name: filter[group_id]
          in: query
          description: ''
          required: false
          style: form
          explode: true
          schema:
            type: integer
            example: 0
        - name: filter[group_name]
          in: query
          description: ''
          required: false
          style: form
          explode: true
          schema:
            type: string
            example: ''
        - name: page
          in: query
          description: ''
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 0
      responses:
        '200':
          description: 'Retorna lista paginada de clientes'
          headers: {}
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: {}
  /customer_groups:
    post:
      tags:
        - Misc
      summary: Adiciona cliente a um grupo
      operationId: AddCustomertoGroup
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCustomertoGroupRequest'
            example:
              customer_id: 1
              group_id: 1
        required: true
      responses:
        '200':
          description: 'Adiciona cliente ao grupo'
          headers: {}
        '404':
          description: 'Cliente ou grupo não encontrado'
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: {}
  /customer_groups/{customerId}:
    parameters:
      - name: customerId
        in: path
        required: true
        description: Id do grupo que será removido
        schema:
          type: integer
          format: int64
          minimum: 1
          example: 1
    delete:
      tags:
        - Misc
      summary: Remove cliente de grupo
      operationId: RemoveCustomerFromGroup
      parameters: []
      responses:
        '200':
          description: 'Remove cliente de grupo'
          headers: {}
        '404':
          description: 'Cliente não encontrado'
      deprecated: false
      servers:
        - url: http://localhost:8085/api
          variables: {}
components:
  schemas:
    AuthRequest:
      title: AuthRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: admin@admin.com
        password: admin
    CreateGroupsRequest:
      title: CreateGroupsRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
      example:
        name: Grupo teste
    UpdateGroupRequest:
      title: UpdateGroupRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
      example:
        name: Teste 2
    AddCustomertoGroupRequest:
      title: AddCustomertoGroupRequest
      required:
        - customer_id
        - group_id
      type: object
      properties:
        customer_id:
          type: integer
          format: int32
        group_id:
          type: integer
          format: int32
      example:
        customer_id: 1
        group_id: 1
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security:
  - bearer: []
tags:
  - name: Misc
    description: ''

